title: Andrey Ivanov # your name (or website title) here
logo: "/images/portfolio_logo.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  AI Algorithm Leader | Real-Time CV/DL Solutions | Expert in Face & Hand Tracking, Gaze, Optometry
  <br><br>
  <a href="https://www.linkedin.com/in/andrey-ivanov1/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
class: wide

url: "https://ivaandrey.github.io"
baseurl: "/portfolio"
